displayName: "ReProxied"
type: middleware

import: github.com/nilskohrs/reproxied

summary: "Route an incoming request through a proxy"

testData:
  proxy: http://proxyHost:3128
  targetHost: https://example.com